### ISSUE TITLE
wish: update README to illustrate what sample 'response' structures look like

### ISSUE THREAD

**Issue by markstos** [desmondmorris/node-geocodio#1]
... or at least drop some links into the README to the relevant external docs.

Looking forward to trying this out!

**Comment by desmondmorris** [comment]
@markstos and a year later... I have update this library :) 

Inline links to the geocodio docs:
 https://github.com/desmondmorris/node-geocodio/commit/0f5e95a3984977ff41f6c6b8757c900ce12e225d
