### ISSUE TITLE
wish: make breaking API change so that "single address" call uses the geocod.io "single address" API

### ISSUE THREAD

**Issue by markstos** [desmondmorris/node-geocodio#2]
I found that the "single address" interface in this module is actually using the batch web service API, so that to get a single coordinate pair ends up looking like this:

   var lng = response.results[0].response.results[0]["location"].lng;
   var lat = response.results[0].response.results[0]["location"].lat;

I believe if the single address API was used instead, this would simplifed to:

    var lng = response.results[0]["location"].lng;
    var lat  = response.results[0]["location"].lat;

That's still a little uglier than I'd like when just want quick access to the first result, but it's better than before.

**Comment by desmondmorris** [comment]
@markstos the library no longer uses the batch endpoint for single and bulk requests.  When passing a single address, the response is now represents what would be expected per  the API docs.
